// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.5.0
// source: job_public.proto

package youtu_job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_INIT   JobStatus = 0 // unused
	JobStatus_WAIT   JobStatus = 1
	JobStatus_START  JobStatus = 2 // unused
	JobStatus_RUN    JobStatus = 3
	JobStatus_STOP   JobStatus = 4 // unused
	JobStatus_FAIL   JobStatus = 5
	JobStatus_CANCEL JobStatus = 6
	JobStatus_DONE   JobStatus = 7
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "INIT",
		1: "WAIT",
		2: "START",
		3: "RUN",
		4: "STOP",
		5: "FAIL",
		6: "CANCEL",
		7: "DONE",
	}
	JobStatus_value = map[string]int32{
		"INIT":   0,
		"WAIT":   1,
		"START":  2,
		"RUN":    3,
		"STOP":   4,
		"FAIL":   5,
		"CANCEL": 6,
		"DONE":   7,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_job_public_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_job_public_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *JobStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = JobStatus(num)
	return nil
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_job_public_proto_rawDescGZIP(), []int{0}
}

var File_job_public_proto protoreflect.FileDescriptor

var file_job_public_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6a, 0x6f, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e, 0x6a, 0x6f, 0x62, 0x2a, 0x5d, 0x0a,
	0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e,
	0x49, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55, 0x4e,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x41, 0x49, 0x4c, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c,
	0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x07, 0x42, 0x0f, 0x5a, 0x0d,
	0x61, 0x70, 0x69, 0x2f, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x5f, 0x6a, 0x6f, 0x62,
}

var (
	file_job_public_proto_rawDescOnce sync.Once
	file_job_public_proto_rawDescData = file_job_public_proto_rawDesc
)

func file_job_public_proto_rawDescGZIP() []byte {
	file_job_public_proto_rawDescOnce.Do(func() {
		file_job_public_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_public_proto_rawDescData)
	})
	return file_job_public_proto_rawDescData
}

var file_job_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_public_proto_goTypes = []interface{}{
	(JobStatus)(0), // 0: youtu.job.JobStatus
}
var file_job_public_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_public_proto_init() }
func file_job_public_proto_init() {
	if File_job_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_public_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_public_proto_goTypes,
		DependencyIndexes: file_job_public_proto_depIdxs,
		EnumInfos:         file_job_public_proto_enumTypes,
	}.Build()
	File_job_public_proto = out.File
	file_job_public_proto_rawDesc = nil
	file_job_public_proto_goTypes = nil
	file_job_public_proto_depIdxs = nil
}
