// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.5.0
// source: zeus_inner.proto

package youtu_zeus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Communicate With Feature Manager
type PageItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId       *string    `protobuf:"bytes,1,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	Version      *int64     `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Items        []*FeaItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	GroupVersion *int64     `protobuf:"varint,4,opt,name=group_version,json=groupVersion" json:"group_version,omitempty"`
}

func (x *PageItem) Reset() {
	*x = PageItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageItem) ProtoMessage() {}

func (x *PageItem) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageItem.ProtoReflect.Descriptor instead.
func (*PageItem) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{0}
}

func (x *PageItem) GetPageId() string {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return ""
}

func (x *PageItem) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *PageItem) GetItems() []*FeaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PageItem) GetGroupVersion() int64 {
	if x != nil && x.GroupVersion != nil {
		return *x.GroupVersion
	}
	return 0
}

type SyncAddFeasReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId    *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items      []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	FeatureIdx *int32      `protobuf:"varint,4,opt,name=feature_idx,json=featureIdx" json:"feature_idx,omitempty"` // =0/1/2
}

func (x *SyncAddFeasReq) Reset() {
	*x = SyncAddFeasReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAddFeasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAddFeasReq) ProtoMessage() {}

func (x *SyncAddFeasReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAddFeasReq.ProtoReflect.Descriptor instead.
func (*SyncAddFeasReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{1}
}

func (x *SyncAddFeasReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncAddFeasReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncAddFeasReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncAddFeasReq) GetFeatureIdx() int32 {
	if x != nil && x.FeatureIdx != nil {
		return *x.FeatureIdx
	}
	return 0
}

type SyncAddFeasRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncAddFeasRsp) Reset() {
	*x = SyncAddFeasRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAddFeasRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAddFeasRsp) ProtoMessage() {}

func (x *SyncAddFeasRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAddFeasRsp.ProtoReflect.Descriptor instead.
func (*SyncAddFeasRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{2}
}

func (x *SyncAddFeasRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncAddFeasRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncAddFeasRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncDeleteFeasReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId   *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items     []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"` // FeaItem不填entity_id, feature_0, feature_1, extend_info
}

func (x *SyncDeleteFeasReq) Reset() {
	*x = SyncDeleteFeasReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDeleteFeasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeleteFeasReq) ProtoMessage() {}

func (x *SyncDeleteFeasReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeleteFeasReq.ProtoReflect.Descriptor instead.
func (*SyncDeleteFeasReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{3}
}

func (x *SyncDeleteFeasReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncDeleteFeasReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncDeleteFeasReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncDeleteFeasRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncDeleteFeasRsp) Reset() {
	*x = SyncDeleteFeasRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDeleteFeasRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeleteFeasRsp) ProtoMessage() {}

func (x *SyncDeleteFeasRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeleteFeasRsp.ProtoReflect.Descriptor instead.
func (*SyncDeleteFeasRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{4}
}

func (x *SyncDeleteFeasRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncDeleteFeasRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncDeleteFeasRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncUpdateFeasReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId    *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items      []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	FeatureIdx *int32      `protobuf:"varint,4,opt,name=feature_idx,json=featureIdx" json:"feature_idx,omitempty"` // =0/1/2
}

func (x *SyncUpdateFeasReq) Reset() {
	*x = SyncUpdateFeasReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateFeasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateFeasReq) ProtoMessage() {}

func (x *SyncUpdateFeasReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateFeasReq.ProtoReflect.Descriptor instead.
func (*SyncUpdateFeasReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{5}
}

func (x *SyncUpdateFeasReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateFeasReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncUpdateFeasReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncUpdateFeasReq) GetFeatureIdx() int32 {
	if x != nil && x.FeatureIdx != nil {
		return *x.FeatureIdx
	}
	return 0
}

type SyncUpdateFeasRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncUpdateFeasRsp) Reset() {
	*x = SyncUpdateFeasRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateFeasRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateFeasRsp) ProtoMessage() {}

func (x *SyncUpdateFeasRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateFeasRsp.ProtoReflect.Descriptor instead.
func (*SyncUpdateFeasRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{6}
}

func (x *SyncUpdateFeasRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateFeasRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncUpdateFeasRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncUpdateEntityIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId   *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items     []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"` // FeaItem 不填feature, extend_info
}

func (x *SyncUpdateEntityIdsReq) Reset() {
	*x = SyncUpdateEntityIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateEntityIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateEntityIdsReq) ProtoMessage() {}

func (x *SyncUpdateEntityIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateEntityIdsReq.ProtoReflect.Descriptor instead.
func (*SyncUpdateEntityIdsReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{7}
}

func (x *SyncUpdateEntityIdsReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateEntityIdsReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncUpdateEntityIdsReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncUpdateEntityIdsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncUpdateEntityIdsRsp) Reset() {
	*x = SyncUpdateEntityIdsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateEntityIdsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateEntityIdsRsp) ProtoMessage() {}

func (x *SyncUpdateEntityIdsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateEntityIdsRsp.ProtoReflect.Descriptor instead.
func (*SyncUpdateEntityIdsRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{8}
}

func (x *SyncUpdateEntityIdsRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateEntityIdsRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncUpdateEntityIdsRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncUpdateFeatureReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId    *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items      []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`                              // FeaItem不填entity_id, extend_info
	FeatureIdx *int32      `protobuf:"varint,4,opt,name=feature_idx,json=featureIdx" json:"feature_idx,omitempty"` // =0/1/2
}

func (x *SyncUpdateFeatureReq) Reset() {
	*x = SyncUpdateFeatureReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateFeatureReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateFeatureReq) ProtoMessage() {}

func (x *SyncUpdateFeatureReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateFeatureReq.ProtoReflect.Descriptor instead.
func (*SyncUpdateFeatureReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{9}
}

func (x *SyncUpdateFeatureReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateFeatureReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncUpdateFeatureReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncUpdateFeatureReq) GetFeatureIdx() int32 {
	if x != nil && x.FeatureIdx != nil {
		return *x.FeatureIdx
	}
	return 0
}

type SyncUpdateFeatureRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncUpdateFeatureRsp) Reset() {
	*x = SyncUpdateFeatureRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateFeatureRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateFeatureRsp) ProtoMessage() {}

func (x *SyncUpdateFeatureRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateFeatureRsp.ProtoReflect.Descriptor instead.
func (*SyncUpdateFeatureRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{10}
}

func (x *SyncUpdateFeatureRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateFeatureRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncUpdateFeatureRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncUpdateExtendInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string     `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId   *string     `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Items     []*PageItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"` // FeaItem不填entity_id, feature_0, feature_1
}

func (x *SyncUpdateExtendInfoReq) Reset() {
	*x = SyncUpdateExtendInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateExtendInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateExtendInfoReq) ProtoMessage() {}

func (x *SyncUpdateExtendInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateExtendInfoReq.ProtoReflect.Descriptor instead.
func (*SyncUpdateExtendInfoReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{11}
}

func (x *SyncUpdateExtendInfoReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateExtendInfoReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncUpdateExtendInfoReq) GetItems() []*PageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncUpdateExtendInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncUpdateExtendInfoRsp) Reset() {
	*x = SyncUpdateExtendInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncUpdateExtendInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdateExtendInfoRsp) ProtoMessage() {}

func (x *SyncUpdateExtendInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdateExtendInfoRsp.ProtoReflect.Descriptor instead.
func (*SyncUpdateExtendInfoRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{12}
}

func (x *SyncUpdateExtendInfoRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncUpdateExtendInfoRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncUpdateExtendInfoRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncTruncateGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId   *string `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
}

func (x *SyncTruncateGroupReq) Reset() {
	*x = SyncTruncateGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTruncateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTruncateGroupReq) ProtoMessage() {}

func (x *SyncTruncateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTruncateGroupReq.ProtoReflect.Descriptor instead.
func (*SyncTruncateGroupReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{13}
}

func (x *SyncTruncateGroupReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncTruncateGroupReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

type SyncTruncateGroupRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncTruncateGroupRsp) Reset() {
	*x = SyncTruncateGroupRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncTruncateGroupRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTruncateGroupRsp) ProtoMessage() {}

func (x *SyncTruncateGroupRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTruncateGroupRsp.ProtoReflect.Descriptor instead.
func (*SyncTruncateGroupRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{14}
}

func (x *SyncTruncateGroupRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncTruncateGroupRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncTruncateGroupRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncClearFeaturesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId    *string `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	FeatureIdx *int32  `protobuf:"varint,3,opt,name=feature_idx,json=featureIdx" json:"feature_idx,omitempty"` // =0/1
}

func (x *SyncClearFeaturesReq) Reset() {
	*x = SyncClearFeaturesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncClearFeaturesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncClearFeaturesReq) ProtoMessage() {}

func (x *SyncClearFeaturesReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncClearFeaturesReq.ProtoReflect.Descriptor instead.
func (*SyncClearFeaturesReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{15}
}

func (x *SyncClearFeaturesReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncClearFeaturesReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncClearFeaturesReq) GetFeatureIdx() int32 {
	if x != nil && x.FeatureIdx != nil {
		return *x.FeatureIdx
	}
	return 0
}

type SyncClearFeaturesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncClearFeaturesRsp) Reset() {
	*x = SyncClearFeaturesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncClearFeaturesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncClearFeaturesRsp) ProtoMessage() {}

func (x *SyncClearFeaturesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncClearFeaturesRsp.ProtoReflect.Descriptor instead.
func (*SyncClearFeaturesRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{16}
}

func (x *SyncClearFeaturesRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncClearFeaturesRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncClearFeaturesRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncPageUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId    *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId      *string `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	PageId       *string `protobuf:"bytes,3,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	FeatureIdx   *int32  `protobuf:"varint,4,opt,name=feature_idx,json=featureIdx" json:"feature_idx,omitempty"` // =0/1/2
	Version      *int64  `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	GroupVersion *int64  `protobuf:"varint,6,opt,name=group_version,json=groupVersion" json:"group_version,omitempty"`
}

func (x *SyncPageUpdateReq) Reset() {
	*x = SyncPageUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPageUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPageUpdateReq) ProtoMessage() {}

func (x *SyncPageUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPageUpdateReq.ProtoReflect.Descriptor instead.
func (*SyncPageUpdateReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{17}
}

func (x *SyncPageUpdateReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncPageUpdateReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncPageUpdateReq) GetPageId() string {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return ""
}

func (x *SyncPageUpdateReq) GetFeatureIdx() int32 {
	if x != nil && x.FeatureIdx != nil {
		return *x.FeatureIdx
	}
	return 0
}

func (x *SyncPageUpdateReq) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SyncPageUpdateReq) GetGroupVersion() int64 {
	if x != nil && x.GroupVersion != nil {
		return *x.GroupVersion
	}
	return 0
}

type SyncPageUpdateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncPageUpdateRsp) Reset() {
	*x = SyncPageUpdateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPageUpdateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPageUpdateRsp) ProtoMessage() {}

func (x *SyncPageUpdateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPageUpdateRsp.ProtoReflect.Descriptor instead.
func (*SyncPageUpdateRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{18}
}

func (x *SyncPageUpdateRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncPageUpdateRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncPageUpdateRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

type SyncNoopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId    *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	GroupId      *string `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	PageId       *string `protobuf:"bytes,3,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	Version      *int64  `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	GroupVersion *int64  `protobuf:"varint,5,opt,name=group_version,json=groupVersion" json:"group_version,omitempty"`
}

func (x *SyncNoopReq) Reset() {
	*x = SyncNoopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncNoopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNoopReq) ProtoMessage() {}

func (x *SyncNoopReq) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNoopReq.ProtoReflect.Descriptor instead.
func (*SyncNoopReq) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{19}
}

func (x *SyncNoopReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncNoopReq) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *SyncNoopReq) GetPageId() string {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return ""
}

func (x *SyncNoopReq) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SyncNoopReq) GetGroupVersion() int64 {
	if x != nil && x.GroupVersion != nil {
		return *x.GroupVersion
	}
	return 0
}

type SyncNoopRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Errorcode *int32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	Errormsg  *string `protobuf:"bytes,3,opt,name=errormsg" json:"errormsg,omitempty"`
}

func (x *SyncNoopRsp) Reset() {
	*x = SyncNoopRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zeus_inner_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncNoopRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNoopRsp) ProtoMessage() {}

func (x *SyncNoopRsp) ProtoReflect() protoreflect.Message {
	mi := &file_zeus_inner_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNoopRsp.ProtoReflect.Descriptor instead.
func (*SyncNoopRsp) Descriptor() ([]byte, []int) {
	return file_zeus_inner_proto_rawDescGZIP(), []int{20}
}

func (x *SyncNoopRsp) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SyncNoopRsp) GetErrorcode() int32 {
	if x != nil && x.Errorcode != nil {
		return *x.Errorcode
	}
	return 0
}

func (x *SyncNoopRsp) GetErrormsg() string {
	if x != nil && x.Errormsg != nil {
		return *x.Errormsg
	}
	return ""
}

var File_zeus_inner_proto protoreflect.FileDescriptor

var file_zeus_inner_proto_rawDesc = []byte{
	0x0a, 0x10, 0x7a, 0x65, 0x75, 0x73, 0x5f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e, 0x7a, 0x65, 0x75, 0x73, 0x1a, 0x0a,
	0x7a, 0x65, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x6f, 0x75, 0x74,
	0x75, 0x2e, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x46, 0x65, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x53,
	0x79, 0x6e, 0x63, 0x41, 0x64, 0x64, 0x46, 0x65, 0x61, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e, 0x7a,
	0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69,
	0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x49, 0x64, 0x78, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x64, 0x64, 0x46,
	0x65, 0x61, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22,
	0x79, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6c, 0x0a, 0x11, 0x53, 0x79,
	0x6e, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x65, 0x61, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x9a, 0x01, 0x0a, 0x11, 0x53, 0x79, 0x6e,
	0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x61, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e,
	0x7a, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f,
	0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x64, 0x78, 0x22, 0x6c, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x65, 0x61, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x73, 0x67, 0x22, 0x7e, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x2e, 0x7a,
	0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x71, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x9d, 0x01, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x6f, 0x75, 0x74, 0x75,
	0x2e, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x5f, 0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x49, 0x64, 0x78, 0x22, 0x6f, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x7f, 0x0a, 0x17, 0x53, 0x79, 0x6e, 0x63, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x6f,
	0x75, 0x74, 0x75, 0x2e, 0x7a, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x72, 0x0a, 0x17, 0x53, 0x79, 0x6e, 0x63,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x50, 0x0a, 0x14,
	0x53, 0x79, 0x6e, 0x63, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x6f,
	0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22,
	0x71, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49,
	0x64, 0x78, 0x22, 0x6f, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6d, 0x73, 0x67, 0x22, 0xc6, 0x01, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x61, 0x67, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x78, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6c, 0x0a, 0x11,
	0x53, 0x79, 0x6e, 0x63, 0x50, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x9f, 0x01, 0x0a, 0x0b, 0x53,
	0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x0b,
	0x53, 0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x6f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x6d, 0x73, 0x67, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x6f, 0x75, 0x74,
	0x75, 0x5f, 0x7a, 0x65, 0x75, 0x73,
}

var (
	file_zeus_inner_proto_rawDescOnce sync.Once
	file_zeus_inner_proto_rawDescData = file_zeus_inner_proto_rawDesc
)

func file_zeus_inner_proto_rawDescGZIP() []byte {
	file_zeus_inner_proto_rawDescOnce.Do(func() {
		file_zeus_inner_proto_rawDescData = protoimpl.X.CompressGZIP(file_zeus_inner_proto_rawDescData)
	})
	return file_zeus_inner_proto_rawDescData
}

var file_zeus_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_zeus_inner_proto_goTypes = []interface{}{
	(*PageItem)(nil),                // 0: youtu.zeus.PageItem
	(*SyncAddFeasReq)(nil),          // 1: youtu.zeus.SyncAddFeasReq
	(*SyncAddFeasRsp)(nil),          // 2: youtu.zeus.SyncAddFeasRsp
	(*SyncDeleteFeasReq)(nil),       // 3: youtu.zeus.SyncDeleteFeasReq
	(*SyncDeleteFeasRsp)(nil),       // 4: youtu.zeus.SyncDeleteFeasRsp
	(*SyncUpdateFeasReq)(nil),       // 5: youtu.zeus.SyncUpdateFeasReq
	(*SyncUpdateFeasRsp)(nil),       // 6: youtu.zeus.SyncUpdateFeasRsp
	(*SyncUpdateEntityIdsReq)(nil),  // 7: youtu.zeus.SyncUpdateEntityIdsReq
	(*SyncUpdateEntityIdsRsp)(nil),  // 8: youtu.zeus.SyncUpdateEntityIdsRsp
	(*SyncUpdateFeatureReq)(nil),    // 9: youtu.zeus.SyncUpdateFeatureReq
	(*SyncUpdateFeatureRsp)(nil),    // 10: youtu.zeus.SyncUpdateFeatureRsp
	(*SyncUpdateExtendInfoReq)(nil), // 11: youtu.zeus.SyncUpdateExtendInfoReq
	(*SyncUpdateExtendInfoRsp)(nil), // 12: youtu.zeus.SyncUpdateExtendInfoRsp
	(*SyncTruncateGroupReq)(nil),    // 13: youtu.zeus.SyncTruncateGroupReq
	(*SyncTruncateGroupRsp)(nil),    // 14: youtu.zeus.SyncTruncateGroupRsp
	(*SyncClearFeaturesReq)(nil),    // 15: youtu.zeus.SyncClearFeaturesReq
	(*SyncClearFeaturesRsp)(nil),    // 16: youtu.zeus.SyncClearFeaturesRsp
	(*SyncPageUpdateReq)(nil),       // 17: youtu.zeus.SyncPageUpdateReq
	(*SyncPageUpdateRsp)(nil),       // 18: youtu.zeus.SyncPageUpdateRsp
	(*SyncNoopReq)(nil),             // 19: youtu.zeus.SyncNoopReq
	(*SyncNoopRsp)(nil),             // 20: youtu.zeus.SyncNoopRsp
	(*FeaItem)(nil),                 // 21: youtu.zeus.FeaItem
}
var file_zeus_inner_proto_depIdxs = []int32{
	21, // 0: youtu.zeus.PageItem.items:type_name -> youtu.zeus.FeaItem
	0,  // 1: youtu.zeus.SyncAddFeasReq.items:type_name -> youtu.zeus.PageItem
	0,  // 2: youtu.zeus.SyncDeleteFeasReq.items:type_name -> youtu.zeus.PageItem
	0,  // 3: youtu.zeus.SyncUpdateFeasReq.items:type_name -> youtu.zeus.PageItem
	0,  // 4: youtu.zeus.SyncUpdateEntityIdsReq.items:type_name -> youtu.zeus.PageItem
	0,  // 5: youtu.zeus.SyncUpdateFeatureReq.items:type_name -> youtu.zeus.PageItem
	0,  // 6: youtu.zeus.SyncUpdateExtendInfoReq.items:type_name -> youtu.zeus.PageItem
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_zeus_inner_proto_init() }
func file_zeus_inner_proto_init() {
	if File_zeus_inner_proto != nil {
		return
	}
	file_zeus_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_zeus_inner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAddFeasReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAddFeasRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDeleteFeasReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDeleteFeasRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateFeasReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateFeasRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateEntityIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateEntityIdsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateFeatureReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateFeatureRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateExtendInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncUpdateExtendInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTruncateGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncTruncateGroupRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncClearFeaturesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncClearFeaturesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPageUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPageUpdateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncNoopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zeus_inner_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncNoopRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zeus_inner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zeus_inner_proto_goTypes,
		DependencyIndexes: file_zeus_inner_proto_depIdxs,
		MessageInfos:      file_zeus_inner_proto_msgTypes,
	}.Build()
	File_zeus_inner_proto = out.File
	file_zeus_inner_proto_rawDesc = nil
	file_zeus_inner_proto_goTypes = nil
	file_zeus_inner_proto_depIdxs = nil
}
